# Generated by Django 3.1.4 on 2020-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201225_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/home/homepc/PycharmProjects/djangoProject/projects/static/images'),
        ),
    ]
