# Generated by Django 3.1.4 on 2021-01-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210104_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
