# Generated by Django 3.1.4 on 2021-01-05 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210104_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='body',
        ),
    ]
