# Generated by Django 3.1.4 on 2021-01-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210105_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/home/homepc/PycharmProjects/djangoProject/projects/images'),
        ),
    ]
