# Generated by Django 3.1.4 on 2020-12-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_about_me', '0002_auto_20201225_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='author',
            new_name='name',
        ),
    ]
