# Generated by Django 3.1.4 on 2020-12-25 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages_about_me', '0003_auto_20201225_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactme',
            name='replied_to',
            field=models.BooleanField(default=False),
        ),
    ]
