# Generated by Django 3.1.4 on 2020-12-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path='/home/homepc/PycharmProjects/djangoProject/blog/static/images/'),
        ),
    ]
