# Generated by Django 3.1.4 on 2020-12-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201229_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='abs_image',
        ),
        migrations.AddField(
            model_name='post',
            name='rel_image',
            field=models.FileField(default='/imagez/project2.png', upload_to=''),
            preserve_default=False,
        ),
    ]
