# Generated by Django 3.1.4 on 2020-12-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201230_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rel_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='abs_image',
            field=models.FilePathField(path='/home/homepc/PycharmProjects/djangoProject/blog/static/images'),
        ),
    ]
