# Generated by Django 3.1.4 on 2021-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210104_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='ok@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
